### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by peter-clemenko** [tudvari/docker-composer#11]
Typescript typings would be useful for those of us using this in typescript.

**Comment by tudvari** [comment]
@aoighost Thanks for the suggestion, I can put on my todo list or feel free to contribute into the project. :-)

**Comment by tudvari** [comment]
Release 4.0.0 contains the type definitions.

**Comment by tudvari** [comment]
Release 4.0.0 contains the type definitions.
