### ISSUE TITLE
Add support for attachable network and Ipam aux_addresses

### ISSUE THREAD

**Issue by shoxxdj** [tudvari/docker-composer#132]
Hello, 

Can you add the support for this two properties on the schema ? :)

https://docs.docker.com/compose/compose-file/06-networks/#attachable
https://docs.docker.com/compose/compose-file/06-networks/#ipam

Regards,

**Comment by tudvari** [comment]
Hi,

I'm trying to start implementing this, hopefully it will be available in the next version.

**Comment by tudvari** [comment]
Please
