### ISSUE TITLE
Error open schema.json

### ISSUE THREAD

**Issue by andrepurnomo** [tudvari/docker-composer#8]
Hi, i'm found error in your index.js.
Failed to open schema.json, running in ubuntu.

When i try check with
`console.log(fs.existsSync('./schema.json'))`
return false

so i change code in index js 
from
`let schema = JSON.parse(fs.readFileSync('/schema.json'))`
to
`let schema = JSON.parse(fs.readFileSync(__dirname + '/schema.json'))`

Sry for my bad english
Thanks

**Comment by tudvari** [comment]
Hi!

Thank you very much your feedback. I fixed this issue in release 3.1.1, which should be on NPM right now.
